import type { FaqItem, Project, ProjectCategory } from "@/lib/types";

export const navigation = [
  { href: "/projekte", label: "Projekte" },
  { href: "/leistungen", label: "Leistungen" },
  { href: "/ueber-mich", label: "Über mich" },
  { href: "/kontakt", label: "Kontakt" },
];

export const categories: ProjectCategory[] = [
  "Alle Projekte",
  "Wohn- & Essbereiche",
  "Küchen",
  "Schlafzimmer",
  "Home Office",
  "Eingangsbereiche",
  "Bäder",
  "Gesamtkonzepte",
];

const projectImage = (slug: string, file: string, alt: string) => ({
  url: `/images/projects/${slug}/${file}`,
  alt,
});

const projectGallery = (slug: string, title: string, count: number, subject: string) =>
  Array.from({ length: count }, (_, index) =>
    projectImage(slug, `${String(index + 1).padStart(2, "0")}.jpg`, `${title} – ${subject}, Ansicht ${index + 1}`),
  );

export const fallbackProjects: Project[] = [
  {
    slug: "emerald-skyline",
    title: "Emerald Skyline",
    location: "Frankfurt",
    year: 2026,
    category: "Wohn- & Essbereiche",
    categories: ["Wohn- & Essbereiche", "Küchen"],
    categoryCovers: [{ category: "Küchen", image: projectImage("emerald-skyline", "delivery/09.jpg", "Emerald Skyline – Küche") }],
    excerpt: "Olivgrüne Sofalandschaften, Burgundy-Akzente und eine raumhohe Marmormedienwand über den Dächern Frankfurts.",
    description: "Ein offenes Wohnkonzept mit internationalem Charakter, in dem markanter Marmor, dunkles Holz und satte Farbakzente eine luxuriöse, zugleich wohnliche Atmosphäre schaffen.",
    materials: ["Kontrastreicher Marmor", "Dunkles Holz", "Olivgrüner Samt", "Burgundy", "Messing"],
    cover: projectImage("emerald-skyline", "cover.jpg", "Emerald Skyline – offener Wohnbereich mit Marmormedienwand und olivgrüner Sofalandschaft"),
    gallery: [
      projectImage("emerald-skyline", "01.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 1"),
      projectImage("emerald-skyline", "delivery/03.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 2"),
      projectImage("emerald-skyline", "delivery/04.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 3"),
      projectImage("emerald-skyline", "delivery/05.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 4"),
      projectImage("emerald-skyline", "delivery/06.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 5"),
      projectImage("emerald-skyline", "delivery/07.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 6"),
      projectImage("emerald-skyline", "delivery/08.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 7"),
      projectImage("emerald-skyline", "delivery/09.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 8"),
      projectImage("emerald-skyline", "delivery/10.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 9"),
      projectImage("emerald-skyline", "delivery/11.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 10"),
      projectImage("emerald-skyline", "delivery/12.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 11"),
      projectImage("emerald-skyline", "delivery/13.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 12"),
      projectImage("emerald-skyline", "delivery/14.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 13"),
      projectImage("emerald-skyline", "delivery/15.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 14"),
      projectImage("emerald-skyline", "02.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 15"),
      projectImage("emerald-skyline", "03.jpg", "Emerald Skyline – offenes Wohn- und Küchenkonzept, Ansicht 16"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein offenes und großzügiges Wohnkonzept, das kraftvolle Kontraste mit absolutem Wohlbefinden verbindet." },
      { heading: "Das Highlight", text: "Eine raumhohe Medienwand aus edlem, kontrastreichem Marmor und dunklen Holzpaneelen, die durch integrierte Lichtbänder perfekt inszeniert wird." },
      { heading: "Der Kontrast", text: "Eine organisch geformte Sofalandschaft in sattem Olivgrün und tiefe Burgundy-Akzente bringen sofortige Wärme gegen die klaren architektonischen Linien." },
      { heading: "Die Raumstruktur", text: "Eine zarte, dunkle Lamellenwand trennt den gemütlichen Lounge-Bereich ganz leicht auf, ohne den Blick in die offene, luxuriöse Wohnküche im Hintergrund zu versperren." },
      { heading: "Vibe", text: "Ausdrucksstark, hotelartig und mit internationalem Charakter." },
    ],
    order: 1,
  },
  {
    slug: "concrete-calm",
    title: "Concrete Calm",
    location: "Berlin",
    year: 2026,
    category: "Wohn- & Essbereiche",
    excerpt: "Sichtbeton, dunkle Holzpaneele und eine helle Sofalandschaft verbinden urbane Klarheit mit weichem Komfort.",
    description: "Ein großzügiger Berliner Wohnraum, dessen präzise Zonen, kühle Architektur und warme Erdtöne selbstverständlich zusammenfinden.",
    materials: ["Sichtbeton", "Dunkles Holz", "Naturstein", "Helle Textilien", "Warme Erdtöne"],
    cover: projectImage("concrete-calm", "cover.jpg", "Concrete Calm – heller Wohnbereich mit Sichtbetondecke, Holzpaneelwand und Stadtblick"),
    gallery: projectGallery("concrete-calm", "Concrete Calm", 9, "moderner Berliner Wohnraum"),
    storySections: [
      { heading: "Die Vision", text: "Moderner, schlichter Stil trifft auf absoluten Komfort." },
      { heading: "Das Highlight", text: "Eine kunstvoll gestaltete, dunkle Holzpaneelwand, die den offenen Raum mit präziser Logik aufteilt." },
      { heading: "Der Kontrast", text: "Die kühle Wirkung einer Sichtbetondecke, perfekt ausgeglichen durch eine helle, gemütliche Sofalandschaft in warmen Erdtönen." },
      { heading: "Vibe", text: "Clean und großzügig." },
    ],
    order: 2,
    featured: true,
  },
  {
    slug: "midnight-cocoon",
    title: "Midnight Cocoon",
    location: "Berlin",
    year: 2026,
    category: "Bäder",
    excerpt: "Dunkler Naturstein, vertikale Holzlamellen und warmes, verborgenes Licht formen ein luxuriöses Gäste-WC.",
    description: "Ein kompakter Raum wird zum privaten Rückzugsort: monolithische Formen, tiefe Grautöne und skulpturales Licht erzeugen eine exklusive Kokonwirkung.",
    materials: ["Dunkelgrauer Naturstein", "Holzlamellen", "Mattschwarz", "Glas", "Warmes LED-Licht"],
    cover: projectImage("midnight-cocoon", "cover.jpg", "Midnight Cocoon – minimalistisches Gäste-WC aus dunklem Naturstein und schwarzen Elementen"),
    gallery: projectGallery("midnight-cocoon", "Midnight Cocoon", 3, "dunkles Berliner Gäste-WC"),
    storySections: [
      { heading: "Die Vision", text: "Ein minimalistisches Gäste-WC, das pure Eleganz und maximale Privatsphäre auf kompakter Fläche zeigt." },
      { heading: "Das Highlight", text: "Großformatige, dunkelgraue Natursteinwände mit feiner Maserung, die den Raum in ein exklusives Kokon-Gefühl hüllen." },
      { heading: "Der Kontrast", text: "Eine dunkle, vertikale Holzlamellenwand und ein monolithischer, mattschwarzer Waschtisch setzen klare architektonische Linien." },
      { heading: "Das Licht", text: "Versteckte, warme LED-Lichtbänder an den Wänden und skulpturale Spiegel-Leuchten brechen die dunklen Töne sanft auf." },
      { heading: "Vibe", text: "Luxuriös und absolut zeitlos." },
    ],
    order: 3,
  },
  {
    slug: "stone-silence",
    title: "Stone Silence",
    location: "Duisburg",
    year: 2026,
    category: "Bäder",
    excerpt: "Ein monolithisches Natursteinbecken und seidige Grautöne übersetzen städtischen Luxus in absolute Ruhe.",
    description: "Ein klares Badkonzept, das mit wenigen präzisen Gesten arbeitet: großformatiger Stein, rahmenloses Glas und warme Lichtleisten.",
    materials: ["Massiver Naturstein", "Dunkelgraue Großformatfliesen", "Glas", "Mattschwarz", "Warmes Licht"],
    cover: projectImage("stone-silence", "cover.jpg", "Stone Silence – großzügiges graues Badezimmer mit rahmenloser Glasdusche"),
    gallery: projectGallery("stone-silence", "Stone Silence", 3, "Duisburger Natursteinbad"),
    storySections: [
      { heading: "Die Vision", text: "Die kühle, reine Wirkung von modernem, städtischem Luxus." },
      { heading: "Das Highlight", text: "Ein aus einem Stück gefertigtes Waschbecken aus massivem Naturstein vor einer schlichten Glasduschkabine." },
      { heading: "Der Kontrast", text: "Großformatige Fliesen in seidigem Dunkelgrau, sanft beleuchtet durch warme Lichtleisten in den offenen Regalen." },
      { heading: "Vibe", text: "Clean, klar strukturiert und absolut zeitlos." },
    ],
    order: 4,
  },
  {
    slug: "burgundy-residence",
    title: "Burgundy Residence",
    location: "Düsseldorf",
    year: 2026,
    category: "Gesamtkonzepte",
    categories: ["Gesamtkonzepte", "Küchen"],
    categoryCovers: [{ category: "Küchen", image: projectImage("burgundy-residence", "delivery/01.jpg", "Burgundy Residence – Küche") }],
    excerpt: "Burgundy-Marmor, Olivgrün und warme Holzachsen verbinden ein großzügiges Apartment zu einer ausdrucksstarken Wohnwelt.",
    description: "Ein ganzheitliches Apartment-Konzept, in dem jede Zone ihre eigene Identität besitzt und dennoch Teil einer konsequenten, warmen Materialwelt bleibt.",
    materials: ["Burgundy-Marmor", "Olivgrün", "Holzlamellen", "Maßgefertigte Fronten", "Warme Lichtachsen"],
    cover: projectImage("burgundy-residence", "cover.jpg", "Burgundy Residence – Visualisierung eines Badezimmers mit weinrotem Marmor und dunklem Holz"),
    gallery: [
      ...projectGallery("burgundy-residence", "Burgundy Residence", 19, "ganzheitliches Düsseldorfer Apartment"),
      projectImage("burgundy-residence", "delivery/05.jpg", "Burgundy Residence – Küche, zusätzliche Ansicht 5"),
      projectImage("burgundy-residence", "delivery/06.jpg", "Burgundy Residence – Küche, zusätzliche Ansicht 6"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein ganzheitliches, großzügiges Apartment-Konzept voller Wärme, Struktur und wohnlichem Luxus." },
      { heading: "Das Highlight", text: "Die konsequente und mutige Kombination aus tiefem, mattem Weinrot (Burgundy) und edlem Olivgrün, die sich wie ein harmonischer roter Faden durch alle Räume zieht." },
      { heading: "Der Kontrast", text: "Ausdrucksstarke, weinrote Marmorwände in der Küche und im Hauptbad treffen auf zarte Holzlamellen, warme Lichtachsen und schlichte, maßgefertigte Möbelfronten." },
      { heading: "Die Raumstruktur", text: "Jedes Zimmer – von der geselligen Wohnküche über das eindrucksvolle Wohnzimmer bis hin zur geborgenen Master-Suite mit eigener Sofa-Lounge – besitzt seine eigene, klare Zone und strahlt absolute Ruhe aus." },
      { heading: "Vibe", text: "Ausdrucksstark, geborgen und bis ins kleinste Detail durchdacht." },
    ],
    order: 5,
  },
  {
    slug: "parisian-dream",
    title: "Parisian Dream",
    location: "Paris",
    year: 2026,
    category: "Schlafzimmer",
    excerpt: "Eine verträumte Bettnische, florale Tapeten und ein maßgeschneiderter Arbeitsplatz schaffen ein magisches Kinderzimmer.",
    description: "Spielerische Eleganz trifft auf clevere Raumnutzung: ein romantisches Kinderzimmer, das Fantasie, Geborgenheit und Alltagstauglichkeit miteinander verbindet.",
    materials: ["Florale Tapete", "Helle Wandpaneele", "Weiche Textilien", "Messingakzente", "Skulpturales Licht"],
    cover: projectImage("parisian-dream", "cover.jpg", "Parisian Dream – helles Kinderzimmer mit floraler Bettnische und wolkenartiger Pendelleuchte"),
    gallery: projectGallery("parisian-dream", "Parisian Dream", 3, "romantisches Pariser Kinderzimmer"),
    storySections: [
      { heading: "Die Vision", text: "Ein verträumtes und hochfunktionales Kinderzimmer, das spielerische Eleganz mit cleverer Raumnutzung verbindet." },
      { heading: "Das Highlight", text: "Eine gemütliche, wie eine kleine Bühne eingerahmte Bettnische mit verspielter Blumentapete, Lichterketten und weich fließenden Baldachin-Vorhängen." },
      { heading: "Der Kontrast", text: "Cleane, helle Wandpaneele und ein moderner, maßgeschneiderter Arbeitsplatz in der Raumecke halten das Design trotz der verspielten Details strukturiert und ruhig." },
      { heading: "Das Licht", text: "Eine wolkenartige, skulpturale Hängeleuchte im Zentrum sorgt für ein sanftes, magisches Lichtgefühl im gesamten Raum." },
      { heading: "Vibe", text: "Romantisch, fantasievoll und mit ganz viel Pariser Charme." },
    ],
    order: 6,
  },
  {
    slug: "koeln-2026",
    title: "Köln 2026",
    location: "Köln",
    year: 2026,
    category: "Küchen",
    categories: ["Küchen","Wohn- & Essbereiche"],
    categoryCovers: [{ category: "Küchen", image: projectImage("koeln-2026", "MAIN.jpg", "Köln 2026 – Küchen") }, { category: "Wohn- & Essbereiche", image: projectImage("koeln-2026", "01.jpg", "Köln 2026 – Wohn- & Essbereiche") }],
    excerpt: "Eine offene Wohnküche mit Essplatz, die Ruhe und Weitblick in den Alltag holt.",
    description: "Eine offene Wohnküche mit Essplatz, die Ruhe und Weitblick in den Alltag holt.",
    materials: ["Heller Naturstein","Dunkles Holz","Sichtbeton","Cremeweiße Textilien"],
    cover: projectImage("koeln-2026", "MAIN.jpg", "Köln 2026 – Küchen, Hauptansicht"),
    gallery: [
      projectImage("koeln-2026", "01.jpg", "Köln 2026 – Küchen, Ansicht 1"),
      projectImage("koeln-2026", "02.jpg", "Köln 2026 – Küchen, Ansicht 2"),
      projectImage("koeln-2026", "03.jpg", "Köln 2026 – Küchen, Ansicht 3"),
      projectImage("koeln-2026", "04.jpg", "Köln 2026 – Küchen, Ansicht 4"),
      projectImage("koeln-2026", "05.jpg", "Köln 2026 – Küchen, Ansicht 5"),
      projectImage("koeln-2026", "06.jpg", "Köln 2026 – Küchen, Ansicht 6"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Eine offene Wohnküche mit Essplatz, die Ruhe und Weitblick in den Alltag holt." },
      { heading: "Das Highlight", text: "Die Kochinsel aus hellem Naturstein mit integrierter Theke. Darüber schwebt eine filigrane Gruppe geometrischer Pendelleuchten." },
      { heading: "Der Kontrast", text: "Dunkle Holzfronten und eine rohe Betondecke treffen auf helle Steinflächen und weiche, cremeweiße Sessel am Esstisch." },
      { heading: "Die Raumstruktur", text: "Ein raumhoher Einbau in dunklem Holz gliedert die Fläche zwischen Küche und Essplatz, ohne den Blick durch die großen Fenster zu verstellen." },
      { heading: "Vibe", text: "Urban, ruhig und großzügig." },
    ],
    order: 7,
  },
  {
    slug: "offenbach-2026",
    title: "Offenbach 2026",
    location: "Offenbach",
    year: 2026,
    category: "Küchen",
    categories: ["Küchen"],
    categoryCovers: [{ category: "Küchen", image: projectImage("offenbach-2026", "MAIN.jpg", "Offenbach 2026 – Küchen") }],
    excerpt: "Eine kompakte Küche, die zeigt, wie viel Charakter auf wenig Fläche passt.",
    description: "Eine kompakte Küche, die zeigt, wie viel Charakter auf wenig Fläche passt.",
    materials: ["Helles Holz","Rosé","Goldene Details","Taupe"],
    cover: projectImage("offenbach-2026", "MAIN.jpg", "Offenbach 2026 – Küchen, Hauptansicht"),
    gallery: [
      projectImage("offenbach-2026", "01.jpg", "Offenbach 2026 – Küchen, Ansicht 1"),
      projectImage("offenbach-2026", "02.jpg", "Offenbach 2026 – Küchen, Ansicht 2"),
      projectImage("offenbach-2026", "03.jpg", "Offenbach 2026 – Küchen, Ansicht 3"),
      projectImage("offenbach-2026", "04.jpg", "Offenbach 2026 – Küchen, Ansicht 4"),
      projectImage("offenbach-2026", "05.jpg", "Offenbach 2026 – Küchen, Ansicht 5"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Eine kompakte Küche, die zeigt, wie viel Charakter auf wenig Fläche passt." },
      { heading: "Das Highlight", text: "Die lange Fensterbank wird zur Frühstücksbar mit Blick über die Stadt. Dazu samtige Barhocker in Rosé." },
      { heading: "Der Kontrast", text: "Strukturierte Fronten in hellem Holzton, zarte Rosétöne und goldene Details treffen auf ein ruhiges Taupe an den Wänden." },
      { heading: "Die Raumstruktur", text: "Hochschränke bis unter die Decke schaffen Stauraum. Die Arbeitsfläche läuft durchgehend an der Wand entlang, der Fensterplatz bleibt frei." },
      { heading: "Vibe", text: "Leicht, verspielt und alltagstauglich." },
    ],
    order: 8,
  },
  {
    slug: "essen-2026",
    title: "Essen 2026",
    location: "Essen",
    year: 2026,
    category: "Bäder",
    categories: ["Bäder"],
    categoryCovers: [{ category: "Bäder", image: projectImage("essen-2026", "MAIN.jpg", "Essen 2026 – Bäder") }],
    excerpt: "Ein Badezimmer, das sich wie ein privates Spa anfühlt.",
    description: "Ein Badezimmer, das sich wie ein privates Spa anfühlt.",
    materials: ["Rot geäderter Naturstein","Dunkles Holz","Beton","Messing"],
    cover: projectImage("essen-2026", "MAIN.jpg", "Essen 2026 – Bäder, Hauptansicht"),
    gallery: [
      projectImage("essen-2026", "01.jpg", "Essen 2026 – Bäder, Ansicht 1"),
      projectImage("essen-2026", "02.jpg", "Essen 2026 – Bäder, Ansicht 2"),
      projectImage("essen-2026", "03.jpg", "Essen 2026 – Bäder, Ansicht 3"),
      projectImage("essen-2026", "04.jpg", "Essen 2026 – Bäder, Ansicht 4"),
      projectImage("essen-2026", "05.jpg", "Essen 2026 – Bäder, Ansicht 5"),
      projectImage("essen-2026", "06.jpg", "Essen 2026 – Bäder, Ansicht 6"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Badezimmer, das sich wie ein privates Spa anfühlt." },
      { heading: "Das Highlight", text: "Der Waschtisch aus charakterstarkem, rot geädertem Naturstein mit Aufsatzbecken in Steinoptik und Armaturen in Messing." },
      { heading: "Der Kontrast", text: "Dunkles Holz und kühle Betonstrukturen treffen auf eine botanische Wandgestaltung und frisches Grün." },
      { heading: "Die Raumstruktur", text: "Eine Dusche hinter Glas mit Messingrahmen, ein wandhängendes WC und viel Stauraum in einem raumhohen Holzschrank." },
      { heading: "Vibe", text: "Warm, sinnlich und hotelartig." },
    ],
    order: 9,
  },
  {
    slug: "krefeld-2026",
    title: "Krefeld 2026",
    location: "Krefeld",
    year: 2026,
    category: "Bäder",
    categories: ["Bäder"],
    categoryCovers: [{ category: "Bäder", image: projectImage("krefeld-2026", "MAIN.jpg", "Krefeld 2026 – Bäder") }],
    excerpt: "Ein Gäste-WC, das mehr ist als ein Funktionsraum. Ein kleiner Auftritt für jeden Besuch.",
    description: "Ein Gäste-WC, das mehr ist als ein Funktionsraum. Ein kleiner Auftritt für jeden Besuch.",
    materials: ["Dunkler Naturstein","Holz","Gedecktes Grün","Tulpen-Wandgestaltung"],
    cover: projectImage("krefeld-2026", "MAIN.jpg", "Krefeld 2026 – Bäder, Hauptansicht"),
    gallery: [
      projectImage("krefeld-2026", "01.jpg", "Krefeld 2026 – Bäder, Ansicht 1"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Gäste-WC, das mehr ist als ein Funktionsraum. Ein kleiner Auftritt für jeden Besuch." },
      { heading: "Das Highlight", text: "Die großformatige Tulpen-Wandgestaltung, die dem Raum etwas Poetisches gibt." },
      { heading: "Der Kontrast", text: "Dunkler, geäderter Stein und Holz treffen auf gedecktes Grün und runde Leuchtobjekte an der Spiegelwand." },
      { heading: "Die Raumstruktur", text: "Waschtisch, Handtuchheizkörper und WC liegen klar in einer Linie. Der Spiegel lässt den schmalen Raum großzügiger wirken." },
      { heading: "Vibe", text: "Poetisch, dunkel und elegant." },
    ],
    order: 10,
  },
  {
    slug: "duisburg-2026",
    title: "Duisburg 2026",
    location: "Duisburg",
    year: 2026,
    category: "Bäder",
    categories: ["Bäder"],
    categoryCovers: [{ category: "Bäder", image: projectImage("duisburg-2026", "MAIN.jpg", "Duisburg 2026 – Bäder") }],
    excerpt: "Ein Bad mit Weitblick, klar und reduziert wie eine Suite.",
    description: "Ein Bad mit Weitblick, klar und reduziert wie eine Suite.",
    materials: ["Grauer Naturstein","Schwarze Armaturen","Dunkles Holz","Glas"],
    cover: projectImage("duisburg-2026", "MAIN.jpg", "Duisburg 2026 – Bäder, Hauptansicht"),
    gallery: [
      projectImage("duisburg-2026", "01.jpg", "Duisburg 2026 – Bäder, Ansicht 1"),
      projectImage("duisburg-2026", "02.jpg", "Duisburg 2026 – Bäder, Ansicht 2"),
      projectImage("duisburg-2026", "03.jpg", "Duisburg 2026 – Bäder, Ansicht 3"),
      projectImage("duisburg-2026", "04.jpg", "Duisburg 2026 – Bäder, Ansicht 4"),
      projectImage("duisburg-2026", "05.jpg", "Duisburg 2026 – Bäder, Ansicht 5"),
      projectImage("duisburg-2026", "06.jpg", "Duisburg 2026 – Bäder, Ansicht 6"),
      projectImage("duisburg-2026", "07.jpg", "Duisburg 2026 – Bäder, Ansicht 7"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Bad mit Weitblick, klar und reduziert wie eine Suite." },
      { heading: "Das Highlight", text: "Die freistehende Badewanne direkt am Fenster, mit Blick über die Stadt." },
      { heading: "Der Kontrast", text: "Großformatiger grauer Naturstein und schwarze Armaturen treffen auf warm beleuchtete Regale in dunklem Holz." },
      { heading: "Die Raumstruktur", text: "Eine Glaswand trennt die Dusche ab. Zwei Waschbecken auf einer durchgehenden Steinplatte geben beiden genug Platz." },
      { heading: "Vibe", text: "Puristisch, ruhig und großstädtisch." },
    ],
    order: 11,
  },
  {
    slug: "muelheim-an-der-ruhr-2026",
    title: "Mülheim an der Ruhr 2026",
    location: "Mülheim an der Ruhr",
    year: 2026,
    category: "Eingangsbereiche",
    categories: ["Eingangsbereiche"],
    categoryCovers: [{ category: "Eingangsbereiche", image: projectImage("muelheim-an-der-ruhr-2026", "MAIN.jpg", "Mülheim an der Ruhr 2026 – Eingangsbereiche") }],
    excerpt: "Ein Eingangsbereich, der schon beim Ankommen zeigt, wie die Wohnung lebt.",
    description: "Ein Eingangsbereich, der schon beim Ankommen zeigt, wie die Wohnung lebt.",
    materials: ["Dunkles Holz","Glas","Grüner Samt","Beton"],
    cover: projectImage("muelheim-an-der-ruhr-2026", "MAIN.jpg", "Mülheim an der Ruhr 2026 – Eingangsbereiche, Hauptansicht"),
    gallery: [
      projectImage("muelheim-an-der-ruhr-2026", "01.jpg", "Mülheim an der Ruhr 2026 – Eingangsbereiche, Ansicht 1"),
      projectImage("muelheim-an-der-ruhr-2026", "02.jpg", "Mülheim an der Ruhr 2026 – Eingangsbereiche, Ansicht 2"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Eingangsbereich, der schon beim Ankommen zeigt, wie die Wohnung lebt." },
      { heading: "Das Highlight", text: "Der raumhohe Garderobenschrank mit Glasfronten und integriertem Licht. Kleidung wird hier wie in einer Boutique inszeniert." },
      { heading: "Der Kontrast", text: "Eine Sitzbank in sattem Grünsamt setzt einen Akzent zwischen dunklem Holz, Beton und hellem Boden." },
      { heading: "Die Raumstruktur", text: "Dunkle Lamellenelemente führen vom Eingang in den offenen Wohn- und Essbereich und lassen trotzdem Blickachsen frei." },
      { heading: "Vibe", text: "Klar, souverän und einladend." },
    ],
    order: 12,
  },
  {
    slug: "bad-vilbel-2026",
    title: "Bad Vilbel 2026",
    location: "Bad Vilbel",
    year: 2026,
    category: "Eingangsbereiche",
    categories: ["Eingangsbereiche"],
    categoryCovers: [{ category: "Eingangsbereiche", image: projectImage("bad-vilbel-2026", "MAIN.jpg", "Bad Vilbel 2026 – Eingangsbereiche") }],
    excerpt: "Ein schmaler Flur, der zum freundlichsten Raum der Wohnung wird.",
    description: "Ein schmaler Flur, der zum freundlichsten Raum der Wohnung wird.",
    materials: ["Taupe","Rosé","Messing","Helles Sideboard"],
    cover: projectImage("bad-vilbel-2026", "MAIN.jpg", "Bad Vilbel 2026 – Eingangsbereiche, Hauptansicht"),
    gallery: [
      projectImage("bad-vilbel-2026", "01.jpg", "Bad Vilbel 2026 – Eingangsbereiche, Ansicht 1"),
      projectImage("bad-vilbel-2026", "02.jpg", "Bad Vilbel 2026 – Eingangsbereiche, Ansicht 2"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein schmaler Flur, der zum freundlichsten Raum der Wohnung wird." },
      { heading: "Das Highlight", text: "Der Bogenspiegel mit goldenem Rahmen über einem hellen Sideboard mit Bogenfront." },
      { heading: "Der Kontrast", text: "Warmes Taupe an den Wänden, zarte Rosétöne bei Textilien und Blumen und feine Messingdetails." },
      { heading: "Die Raumstruktur", text: "Eine offene Hakenleiste und das schmale Sideboard nutzen die Wand clever. Der Weg bleibt frei." },
      { heading: "Vibe", text: "Sanft, hell und persönlich." },
    ],
    order: 13,
  },
  {
    slug: "wesel-2026",
    title: "Wesel 2026",
    location: "Wesel",
    year: 2026,
    category: "Eingangsbereiche",
    categories: ["Eingangsbereiche"],
    categoryCovers: [{ category: "Eingangsbereiche", image: projectImage("wesel-2026", "MAIN.jpg", "Wesel 2026 – Eingangsbereiche") }],
    excerpt: "Ein Entree mit Haus-Charakter, das warm empfängt und Ordnung schafft.",
    description: "Ein Entree mit Haus-Charakter, das warm empfängt und Ordnung schafft.",
    materials: ["Dunkles Holz","Stein","Heller Holzboden","Warme Orangetöne"],
    cover: projectImage("wesel-2026", "MAIN.jpg", "Wesel 2026 – Eingangsbereiche, Hauptansicht"),
    gallery: [
      projectImage("wesel-2026", "01.jpg", "Wesel 2026 – Eingangsbereiche, Ansicht 1"),
      projectImage("wesel-2026", "02.jpg", "Wesel 2026 – Eingangsbereiche, Ansicht 2"),
      projectImage("wesel-2026", "03.jpg", "Wesel 2026 – Eingangsbereiche, Ansicht 3"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Entree mit Haus-Charakter, das warm empfängt und Ordnung schafft." },
      { heading: "Das Highlight", text: "Die Treppe mit Steinstufen, die den Blick nach oben zieht und den Eingang mit dem Rest des Hauses verbindet." },
      { heading: "Der Kontrast", text: "Dunkles Holz an Türen und Einbauten trifft auf helle Wände, einen hellen Holzboden und warme Kunst in Orangetönen." },
      { heading: "Die Raumstruktur", text: "Einbauschränke nehmen den Stauraum auf. Ein kleiner Sessel am Fenster schafft einen Platz zum Ankommen." },
      { heading: "Vibe", text: "Warm, klassisch und wohnlich." },
    ],
    order: 14,
  },
  {
    slug: "hanau-2026",
    title: "Hanau 2026",
    location: "Hanau",
    year: 2026,
    category: "Home Office",
    categories: ["Home Office"],
    categoryCovers: [{ category: "Home Office", image: projectImage("hanau-2026", "MAIN.jpg", "Hanau 2026 – Home Office") }],
    excerpt: "Ein Home Office, in dem man gern arbeitet und genauso gern bleibt.",
    description: "Ein Home Office, in dem man gern arbeitet und genauso gern bleibt.",
    materials: ["Rote Wände","Dunkles Holz","Orange","Cognac"],
    cover: projectImage("hanau-2026", "MAIN.jpg", "Hanau 2026 – Home Office, Hauptansicht"),
    gallery: [
      projectImage("hanau-2026", "01.jpg", "Hanau 2026 – Home Office, Ansicht 1"),
      projectImage("hanau-2026", "02.jpg", "Hanau 2026 – Home Office, Ansicht 2"),
      projectImage("hanau-2026", "03.jpg", "Hanau 2026 – Home Office, Ansicht 3"),
      projectImage("hanau-2026", "04.jpg", "Hanau 2026 – Home Office, Ansicht 4"),
      projectImage("hanau-2026", "05.jpg", "Hanau 2026 – Home Office, Ansicht 5"),
      projectImage("hanau-2026", "06.jpg", "Hanau 2026 – Home Office, Ansicht 6"),
      projectImage("hanau-2026", "07.jpg", "Hanau 2026 – Home Office, Ansicht 7"),
      projectImage("hanau-2026", "08.jpg", "Hanau 2026 – Home Office, Ansicht 8"),
      projectImage("hanau-2026", "09.jpg", "Hanau 2026 – Home Office, Ansicht 9"),
      projectImage("hanau-2026", "10.jpg", "Hanau 2026 – Home Office, Ansicht 10"),
      projectImage("hanau-2026", "11.jpg", "Hanau 2026 – Home Office, Ansicht 11"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Home Office, in dem man gern arbeitet und genauso gern bleibt." },
      { heading: "Das Highlight", text: "Die kräftig roten Wände, die dem Raum Tiefe und Wärme geben. Dazu ein offenes Regal in Schwarz." },
      { heading: "Der Kontrast", text: "Warme Orange- und Cognactöne bei Stühlen und Sofa treffen auf dunkles Holz und grafische Kunst." },
      { heading: "Die Raumstruktur", text: "Schreibtisch und Besprechungsplatz auf der einen Seite, eine gemütliche Lounge-Ecke am Fenster auf der anderen." },
      { heading: "Vibe", text: "Mutig, warm und inspirierend." },
    ],
    order: 15,
  },
  {
    slug: "oberhausen-2026",
    title: "Oberhausen 2026",
    location: "Oberhausen",
    year: 2026,
    category: "Home Office",
    categories: ["Home Office"],
    categoryCovers: [{ category: "Home Office", image: projectImage("oberhausen-2026", "MAIN.jpg", "Oberhausen 2026 – Home Office") }],
    excerpt: "Ein ruhiges Arbeitszimmer mit Großstadtblick, das Fokus und Rückzug vereint.",
    description: "Ein ruhiges Arbeitszimmer mit Großstadtblick, das Fokus und Rückzug vereint.",
    materials: ["Beton","Dunkles Holz","Glas","Grün","Orange"],
    cover: projectImage("oberhausen-2026", "MAIN.jpg", "Oberhausen 2026 – Home Office, Hauptansicht"),
    gallery: [
      projectImage("oberhausen-2026", "01.jpg", "Oberhausen 2026 – Home Office, Ansicht 1"),
      projectImage("oberhausen-2026", "02.jpg", "Oberhausen 2026 – Home Office, Ansicht 2"),
      projectImage("oberhausen-2026", "03.jpg", "Oberhausen 2026 – Home Office, Ansicht 3"),
      projectImage("oberhausen-2026", "04.jpg", "Oberhausen 2026 – Home Office, Ansicht 4"),
      projectImage("oberhausen-2026", "05.jpg", "Oberhausen 2026 – Home Office, Ansicht 5"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein ruhiges Arbeitszimmer mit Großstadtblick, das Fokus und Rückzug vereint." },
      { heading: "Das Highlight", text: "Die Gruppe gläserner Kugelleuchten an der dunklen Holzwand, die wie ein Kunstobjekt wirkt." },
      { heading: "Der Kontrast", text: "Rohe Betonwände und dunkles Holz treffen auf ein grünes Sofa und Akzente in Orange." },
      { heading: "Die Raumstruktur", text: "Ein integrierter Schreibtisch mit Regalnische auf der einen Seite, ein Sofa als Lese- und Gästeplatz auf der anderen." },
      { heading: "Vibe", text: "Urban, fokussiert und entspannt." },
    ],
    order: 16,
  },
  {
    slug: "wiesbaden-2026",
    title: "Wiesbaden 2026",
    location: "Wiesbaden",
    year: 2026,
    category: "Schlafzimmer",
    categories: ["Schlafzimmer"],
    categoryCovers: [{ category: "Schlafzimmer", image: projectImage("wiesbaden-2026", "MAIN.jpg", "Wiesbaden 2026 – Schlafzimmer") }],
    excerpt: "Ein Schlafzimmer mit Persönlichkeit, das Sammelstücke und Alltag zusammenbringt.",
    description: "Ein Schlafzimmer mit Persönlichkeit, das Sammelstücke und Alltag zusammenbringt.",
    materials: ["Grauer Putz","Holz","Rote Decke","Schachbrettmuster"],
    cover: projectImage("wiesbaden-2026", "MAIN.jpg", "Wiesbaden 2026 – Schlafzimmer, Hauptansicht"),
    gallery: [
      projectImage("wiesbaden-2026", "01.jpg", "Wiesbaden 2026 – Schlafzimmer, Ansicht 1"),
      projectImage("wiesbaden-2026", "02.jpg", "Wiesbaden 2026 – Schlafzimmer, Ansicht 2"),
      projectImage("wiesbaden-2026", "03.jpg", "Wiesbaden 2026 – Schlafzimmer, Ansicht 3"),
      projectImage("wiesbaden-2026", "04.jpg", "Wiesbaden 2026 – Schlafzimmer, Ansicht 4"),
      projectImage("wiesbaden-2026", "05.jpg", "Wiesbaden 2026 – Schlafzimmer, Ansicht 5"),
      projectImage("wiesbaden-2026", "06.jpg", "Wiesbaden 2026 – Schlafzimmer, Ansicht 6"),
      projectImage("wiesbaden-2026", "07.jpg", "Wiesbaden 2026 – Schlafzimmer, Ansicht 7"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Schlafzimmer mit Persönlichkeit, das Sammelstücke und Alltag zusammenbringt." },
      { heading: "Das Highlight", text: "Die Decke in kräftigem Rot, die den Raum zusammenhält und ihm sofort Charakter gibt." },
      { heading: "Der Kontrast", text: "Ein grafisches Schachbrettmuster am Boden trifft auf graue Putzwände, Vintage-Stücke wie das Grammofon und warme Holzdetails." },
      { heading: "Die Raumstruktur", text: "Bett, Schreibplatz am Fenster und eine offene Kleiderstange sind klar verteilt. So wirkt der Raum aufgeräumt." },
      { heading: "Vibe", text: "Individuell, lässig und kreativ." },
    ],
    order: 17,
  },
  {
    slug: "bad-homburg-2026",
    title: "Bad Homburg 2026",
    location: "Bad Homburg",
    year: 2026,
    category: "Schlafzimmer",
    categories: ["Schlafzimmer"],
    categoryCovers: [{ category: "Schlafzimmer", image: projectImage("bad-homburg-2026", "MAIN.jpg", "Bad Homburg 2026 – Schlafzimmer") }],
    excerpt: "Ein Schlafzimmer mit Hotelgefühl, zum Ankommen und Durchatmen.",
    description: "Ein Schlafzimmer mit Hotelgefühl, zum Ankommen und Durchatmen.",
    materials: ["Nussholz","Salbeigrüne Textilien","Rote Decke","Glas"],
    cover: projectImage("bad-homburg-2026", "MAIN.jpg", "Bad Homburg 2026 – Schlafzimmer, Hauptansicht"),
    gallery: [
      projectImage("bad-homburg-2026", "01.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 1"),
      projectImage("bad-homburg-2026", "02.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 2"),
      projectImage("bad-homburg-2026", "03.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 3"),
      projectImage("bad-homburg-2026", "04.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 4"),
      projectImage("bad-homburg-2026", "05.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 5"),
      projectImage("bad-homburg-2026", "06.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 6"),
      projectImage("bad-homburg-2026", "07.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 7"),
      projectImage("bad-homburg-2026", "08.jpg", "Bad Homburg 2026 – Schlafzimmer, Ansicht 8"),
    ],
    storySections: [
      { heading: "Die Vision", text: "Ein Schlafzimmer mit Hotelgefühl, zum Ankommen und Durchatmen." },
      { heading: "Das Highlight", text: "Der skulpturale Kronleuchter aus hellen, blattartigen Elementen über dem Bett." },
      { heading: "Der Kontrast", text: "Eine Decke in tiefem Rot und dunkles Nussholz treffen auf helle Wandflächen und Textilien in Salbeigrün." },
      { heading: "Die Raumstruktur", text: "Ein raumhoher Kleiderschrank, eine Vitrinenwand mit Lowboard und ein Ankleidebereich mit Spiegel geben jedem Bereich seinen Platz." },
      { heading: "Vibe", text: "Elegant, geborgen und hotelartig." },
    ],
    order: 18,
  },
];

export const packageTerms = "Bis zu zwei Korrekturschleifen inklusive. Alle Preise sind Endpreise. Gemäß § 19 Abs. 1 UStG wird keine Umsatzsteuer berechnet.";

export const packages = [
  {
    name: "Édition Unique",
    eyebrow: "Das Gesamtkonzept",
    description: "Das Rundum-sorglos-Paket für dein neues Zuhause.",
    features: ["2D-Planung", "Produktempfehlungen", "3D-Visualisierung", "Das Édition Reveal"],
    price: "129 € / m²",
    priceValue: 129,
    priceCurrency: "EUR",
    priceUnit: "m²",
  },
];

export const services = [
  {
    title: "Accessoire-Einkauf (Full-Service)",
    text: "Wir übernehmen die gesamte Auswahl und Bestellung dekorativer Details wie Vasen, Bücher oder Kissen.",
    price: "Artikelpreis + 20% Servicepauschale",
  },
  {
    title: "Express-Service (72h-Konzept-Entwurf)",
    text: "Für eilige Projekte: Priorisierte Bearbeitung mit schneller Konzeptlieferung – je nach Verfügbarkeit.",
    price: "+20%",
  },
  {
    title: "Zusätzliche Visualisierung / Überarbeitung",
    text: "Enthält eine weitere 3D-Visualisierung oder konzeptionelle Anpassung nach der zweiten Korrekturschleife. Ideal bei Änderungswünschen, die über das vereinbarte Maß hinausgehen.",
    price: "49€/QM",
  },
  {
    title: "Shopping-Service & Produktbestellung",
    text: "Wir übernehmen die komplette Abwicklung deiner Bestellungen – von der Recherche bis zur Bestellung inklusive Rücksprachen mit Lieferanten.",
    price: "Artikelpreis + 20% Servicepauschale",
  },
  {
    title: "Projektkoordination & Handwerkersteuerung",
    text: "Organisation und Kommunikation mit allen Gewerken. Bauleitung light für einen reibungslosen Ablauf vor Ort.",
    price: "245 €/Stunde",
  },
  {
    title: "Nachhaltiges Design (Eco friendly Konzept)",
    text: "Materialien und Produkte aus nachhaltiger Produktion, ganzheitlich gedacht für ein bewusstes Zuhause.",
    price: "258 €/QM",
  },
];

export const serviceFaqs: FaqItem[] = [
  {
    question: "Bietet ihr auch technische Zeichnungen an?",
    answer: "Aktuell nicht. Ich arbeite noch ohne festen Architekten und möchte diese Verantwortung nicht ohne Fachpartner übernehmen. Sobald ich mit einem Architekten zusammenarbeite, wird das Teil des Angebots.",
  },
  {
    question: "Wo bietet ANNA ÉDITION Interior Design an?",
    answer: "ANNA ÉDITION hat seinen Sitz in Wesel und begleitet Interior-Design-Projekte am Niederrhein, unter anderem in Duisburg und Düsseldorf, sowie im Großraum Frankfurt am Main (im Umkreis von 50 km). Online-Einrichtungsberatungen sind deutschlandweit möglich.",
  },
  {
    question: "Wie funktioniert eine Online-Einrichtungsberatung?",
    answer: "Nach deiner Anfrage besprechen wir Raum, Wünsche und Budget. Auf Basis deiner Unterlagen erhältst du eine klare gestalterische Richtung, konkrete Empfehlungen und mit Édition Unique eine 2D-Planung, Produktempfehlungen, eine 3D-Visualisierung und das Édition Reveal.",
  },
  {
    question: "Was ist in einer 3D-Visualisierung enthalten?",
    answer: "Die realistische 3D-Visualisierung zeigt die geplante Raumwirkung, Möblierung, Materialien, Farben und Beleuchtung vor der Umsetzung. Der genaue Umfang richtet sich nach deinem Projekt.",
  },
  {
    question: "Wie setzen sich die Preise zusammen?",
    answer: "Édition Unique kostet 129 €/m² und beinhaltet bis zu zwei Korrekturschleifen. Zusatzleistungen können optional ergänzt werden. Alle Preise sind Endpreise. Gemäß § 19 Abs. 1 UStG wird keine Umsatzsteuer berechnet. Vor Projektstart erhältst du eine transparente Zusammenfassung der Leistungen und Kosten.",
  },
  {
    question: "Was ist Call a Designer?",
    answer: "Call a Designer ist eine fokussierte 90-minütige Online-Beratung für konkrete Einrichtungsfragen, eine professionelle Zweitmeinung oder schnelle gestalterische Klarheit. Ein Einkaufsguide ist enthalten. Der Festpreis beträgt 500 Euro.",
  },
  {
    question: "Berechnest du Fahrtkosten für die Vor-Ort-Termine?",
    answer: "Nein, alle Preise sind All-Inclusive-Preise. Da mir eine transparente Partnerschaft auf Augenhöhe wichtig ist, sind sämtliche Reise- und Anfahrtskosten in den Paketpreisen bereits komplett enthalten. Es gibt bei Anna Édition keine versteckten Kosten oder nachträgliche Kilometer-Abrechnungen für dich.",
  },
  {
    question: "Ich wohne im Großraum Frankfurt / Hanau – kann ich dich für ein Vor-Ort-Termine buchen?",
    answer: "Ja, sehr gerne! Ich habe alle zwei Wochen feste Termine in Hessen. Mein Einzugsgebiet umfasst dabei Frankfurt am Main sowie alle Orte im Umkreis von 50 km (wie z. B. Hanau, Offenbach oder Bad Vilbel). Liegt dein Projekt in diesem Radius, profitierst du ohne Aufpreis von meinem All-Inclusive-Modell.",
  },
];
