import type { Metadata } from "next";
import { isIndexableDeployment } from "@/lib/seo";
import { getPageContent } from "@/sanity/queries";

export const metadata: Metadata = {
  title: "Datenschutz",
  alternates: { canonical: "/datenschutz" },
  robots: { index: false, follow: isIndexableDeployment },
};
export default async function PrivacyPage() {
  const page = await getPageContent("datenschutz");
  const sections = page?.sections?.length ? page.sections : [
    { heading: "1. Verantwortliche Stelle", text: "Verantwortlich für die Datenverarbeitung auf dieser Website ist:\n\nANNA ÉDITION\nInhaberin: Anna Matkovic\nKreuzstraße 15\n46483 Wesel\nDeutschland\n\nTelefon: +49 157 5207 9305\nE-Mail: studio@annaedition.de" },
    { heading: "2. Allgemeine Hinweise und Rechtsgrundlagen", text: "Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung einer funktionsfähigen Website, zur sicheren Kommunikation oder zur Bearbeitung deiner Anfrage erforderlich ist. Je nach Zweck erfolgt die Verarbeitung insbesondere auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO (Einwilligung), Art. 6 Abs. 1 lit. b DSGVO (Vertrag oder vorvertragliche Maßnahmen), Art. 6 Abs. 1 lit. c DSGVO (rechtliche Verpflichtung) oder Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse)." },
    { heading: "3. Hosting und Server-Logfiles", text: "Diese Website wird über Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, USA, bereitgestellt. Beim Aufruf der Website können technisch erforderliche Verbindungsdaten verarbeitet werden, insbesondere IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, Referrer, Browser- und Geräteinformationen sowie Status- und Fehlerdaten. Die Verarbeitung dient der sicheren und stabilen Bereitstellung der Website und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Weitere Informationen: https://vercel.com/legal/privacy-notice" },
    { heading: "4. Kontaktformular und Anfragen", text: "Wenn du uns über das Kontaktformular, per E-Mail oder telefonisch kontaktierst, verarbeiten wir die von dir angegebenen Kontaktdaten, Projektangaben und Nachrichten zur Bearbeitung deiner Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit es um die Anbahnung oder Durchführung eines Vertrags geht, ansonsten Art. 6 Abs. 1 lit. f DSGVO. Pflichtangaben sind im Formular entsprechend gekennzeichnet. Eine Weitergabe zu Werbezwecken findet nicht statt." },
    { heading: "5. E-Mail-Versand über Resend", text: "Für den Versand von Anfragen und Eingangsbestätigungen nutzen wir Resend, einen Dienst der Plus Five Five, Inc., 2261 Market Street #5039, San Francisco, CA 94114, USA. Dabei werden insbesondere Name, E-Mail-Adresse, Nachrichteninhalt und technische Versanddaten verarbeitet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b beziehungsweise lit. f DSGVO. Weitere Informationen: https://resend.com/legal/privacy-policy" },
    { heading: "6. Dateiuploads über Vercel Blob", text: "Optional hochgeladene Grundrisse, Moodboards, Bilder und PDF-Dateien werden zur Bearbeitung deiner Anfrage in Vercel Blob gespeichert. Die Links sind technisch öffentlich erreichbar, werden jedoch mit einem zufälligen, schwer zu erratenden Dateinamen erzeugt und nur im Zusammenhang mit deiner Anfrage verwendet. Bitte lade keine nicht erforderlichen oder besonders sensiblen Daten hoch. Uploads werden spätestens 30 Tage nach dem Hochladen automatisiert gelöscht. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO." },
    { heading: "7. Cloudflare Turnstile", text: "Zum Schutz des Kontaktformulars vor automatisierten Eingaben und Missbrauch verwenden wir Cloudflare Turnstile der Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA. Turnstile wertet technische Signale des Browsers und Geräts aus, um zwischen Menschen und automatisierten Zugriffen zu unterscheiden. Dazu können IP-Adresse, Browser- und Geräteinformationen sowie Interaktions- und Prüfungsdaten verarbeitet werden. Die Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO und dient der Sicherheit unserer Formulare. Weitere Informationen: https://developers.cloudflare.com/turnstile/" },
    { heading: "8. Content-Management-System Sanity", text: "Zur Verwaltung redaktioneller Inhalte verwenden wir Sanity. Öffentliche Seiteninhalte können dabei über die Infrastruktur von Sanity geladen werden. Personenbezogene Daten aus Kontaktanfragen werden nicht im CMS gespeichert. Weitere Informationen: https://www.sanity.io/legal/privacy" },
    { heading: "9. Cookies und lokale Speicherungen", text: "Wir verwenden eine technisch notwendige Speicherung namens „anna_cookie_consent“, um deine Datenschutz-Auswahl für 180 Tage zu dokumentieren. Diese Speicherung ist für die Bereitstellung deiner gewählten Einstellungen erforderlich.\n\nWenn du „Alle akzeptieren“ wählst, speichern wir zusätzlich unter „anna-theme“ dein bevorzugtes helles oder dunkles Farbschema für 180 Tage. Diese Komfortspeicherung erfolgt auf Grundlage deiner Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Du kannst deine Auswahl jederzeit über „Cookie-Einstellungen“ im Footer ändern. Analyse-, Profiling- oder Marketing-Cookies werden nicht eingesetzt." },
    { heading: "10. Externe Links und soziale Netzwerke", text: "Unsere Website enthält ausschließlich einfache Links zu Instagram und Pinterest. Beim bloßen Besuch unserer Website werden dadurch keine Inhalte dieser Plattformen geladen. Erst wenn du einen solchen Link aufrufst, verlässt du unsere Website; ab diesem Zeitpunkt gelten die Datenschutzbestimmungen des jeweiligen Anbieters." },
    { heading: "11. Empfänger und Drittlandübermittlungen", text: "Im Rahmen der beschriebenen Zwecke können Vercel, Resend, Cloudflare und Sanity als technische Dienstleister personenbezogene Daten erhalten. Soweit Daten außerhalb der Europäischen Union oder des Europäischen Wirtschaftsraums verarbeitet werden, erfolgt dies nur unter Beachtung der Voraussetzungen der Art. 44 ff. DSGVO, etwa auf Grundlage eines Angemessenheitsbeschlusses oder geeigneter Garantien wie EU-Standardvertragsklauseln." },
    { heading: "12. Speicherdauer", text: "Wir speichern personenbezogene Daten nur so lange, wie dies für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen. Projektanfragen werden nach Abschluss der Kommunikation gelöscht, sofern daraus kein Vertragsverhältnis entsteht und keine gesetzlichen Gründe für eine längere Speicherung vorliegen. Vertrags- und abrechnungsrelevante Daten werden entsprechend den gesetzlichen Aufbewahrungsfristen gespeichert." },
    { heading: "13. Deine Rechte", text: "Du hast im Rahmen der gesetzlichen Voraussetzungen das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung kannst du jederzeit mit Wirkung für die Zukunft widerrufen. Zur Ausübung deiner Rechte genügt eine Nachricht an studio@annaedition.de." },
    { heading: "14. Beschwerderecht", text: "Du hast das Recht, dich bei einer Datenschutzaufsichtsbehörde zu beschweren. Zuständig für Nordrhein-Westfalen ist insbesondere die Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW), Kavalleriestraße 2–4, 40213 Düsseldorf, https://www.ldi.nrw.de/." },
    { heading: "15. Verschlüsselte Übertragung", text: "Diese Website nutzt eine verschlüsselte HTTPS-Verbindung. Dadurch werden Daten, die du an uns übermittelst, während der Übertragung vor dem Zugriff Dritter geschützt." },
  ];
  return (
    <section className="section container legal">
      <p className="eyebrow" data-motion="load">{page?.eyebrow || "Rechtliches"}</p>
      <h1 className="display" data-motion="load" data-motion-order="1">{page?.title || "Datenschutz"}</h1>
      <p className="lede" data-motion="load" data-motion-order="2">{page?.intro || "Hier erfährst du transparent, welche Daten bei der Nutzung unserer Website verarbeitet werden und welche Rechte du hast."}</p>
      {sections.map((section) => <div data-motion="reveal" key={section.heading}><h2>{section.heading}</h2><p className="legal-text">{section.text}</p></div>)}
      <p className="legal-updated">Stand: August 2026</p>
    </section>
  );
}
