import type { Metadata } from "next";
import { isIndexableDeployment } from "@/lib/seo";
import { getPageContent } from "@/sanity/queries";

export const metadata: Metadata = {
  title: "Datenschutz",
  alternates: { canonical: "/datenschutz" },
  robots: { index: false, follow: isIndexableDeployment },
};
export default async function PrivacyPage() {
  const page = await getPageContent("datenschutz");
  const sections = page?.sections?.length ? page.sections : [
    { heading: "1. Verantwortliche Stelle", text: "Verantwortlich für die Datenverarbeitung auf dieser Website ist:\n\nANNA ÉDITION\nInhaberin: Anna Matkovic\nKreuzstraße 15\n46483 Wesel\nDeutschland\n\nTelefon: +49 157 5207 9305\nE-Mail: studio@annaedition.de" },
    { heading: "2. Allgemeine Hinweise und Rechtsgrundlagen", text: "Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung einer funktionsfähigen Website, zur sicheren Kommunikation oder zur Bearbeitung deiner Anfrage erforderlich ist. Je nach Zweck erfolgt die Verarbeitung insbesondere auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO (Einwilligung), Art. 6 Abs. 1 lit. b DSGVO (Vertrag oder vorvertragliche Maßnahmen), Art. 6 Abs. 1 lit. c DSGVO (rechtliche Verpflichtung) oder Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse)." },
    { heading: "3. Hosting und Server-Logfiles", text: "Diese Website wird über Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, USA, bereitgestellt. Beim Aufruf der Website können technisch erforderliche Verbindungsdaten verarbeitet werden, insbesondere IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, Referrer, Browser- und Geräteinformationen sowie Status- und Fehlerdaten. Die Verarbeitung dient der sicheren und stabilen Bereitstellung der Website und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Weitere Informationen: https://vercel.com/legal/privacy-notice" },
    { heading: "4. Kontaktformular und Anfragen", text: "Wenn du uns über das Kontaktformular, per E-Mail oder telefonisch kontaktierst, verarbeiten wir die von dir angegebenen Kontaktdaten, Projektangaben und Nachrichten zur Bearbeitung deiner Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit es um die Anbahnung oder Durchführung eines Vertrags geht, ansonsten Art. 6 Abs. 1 lit. f DSGVO. Pflichtangaben sind im Formular entsprechend gekennzeichnet. Eine Weitergabe zu Werbezwecken findet nicht statt." },
    { heading: "5. E-Mail-Versand über Resend", text: "Für den Versand von Anfragen und Eingangsbestätigungen nutzen wir Resend, einen Dienst der Plus Five Five, Inc., 2261 Market Street #5039, San Francisco, CA 94114, USA. Dabei werden insbesondere Name, E-Mail-Adresse, Nachrichteninhalt und technische Versanddaten verarbeitet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b beziehungsweise lit. f DSGVO. Weitere Informationen: https://resend.com/legal/privacy-policy" },
    { heading: "6. Dateiuploads über Vercel Blob", text: "Optional hochgeladene Grundrisse, Moodboards, Bilder und PDF-Dateien werden zur Bearbeitung deiner Anfrage in Vercel Blob gespeichert. Die Dateien erhalten zufällige Dateinamen ohne den ursprünglichen Dateinamen. Jeder, der über den Link verfügt, kann die Datei ohne Anmeldung abrufen. Bitte entferne nicht erforderliche personenbezogene Angaben aus den Unterlagen und lade keine vertraulichen oder besonders sensiblen Daten hoch. Für vertrauliche Unterlagen kontaktiere uns bitte vorab, um einen geschützten Übertragungsweg zu vereinbaren.\n\nDateien werden nach Ablauf von 30 Tagen beim nächsten täglichen Bereinigungslauf gelöscht, im regulären Betrieb also nach etwa 30 bis 31 Tagen. Dies gilt auch für bereits hochgeladene Dateien, wenn die anschließende Übermittlung der Anfrage fehlschlägt. Die Speicherdauer der Anfrage selbst wird unter „Speicherdauer“ erläutert. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, bei sonstigen Anfragen Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse ist deren Bearbeitung." },
    { heading: "7. Cloudflare Turnstile", text: "Zum Schutz des Kontaktformulars vor automatisierten Eingaben und Missbrauch verwenden wir Cloudflare Turnstile der Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA. Die Sicherheitsprüfung wird im letzten Schritt des Kontaktformulars geladen. Turnstile wertet technische Signale des Browsers und Geräts aus, um zwischen Menschen und automatisierten Zugriffen zu unterscheiden. Dazu können IP-Adresse, Browser- und Geräteinformationen sowie Interaktions- und Prüfungsdaten verarbeitet werden. Die Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO und dient der Sicherheit unserer Formulare. Weitere Informationen: https://www.cloudflare.com/turnstile-privacy-policy/" },
    { heading: "8. Content-Management-System Sanity", text: "Zur Verwaltung redaktioneller Inhalte verwenden wir Sanity. Öffentliche Seiteninhalte können dabei über die Infrastruktur von Sanity geladen werden. Personenbezogene Daten aus Kontaktanfragen werden nicht im CMS gespeichert. Weitere Informationen: https://www.sanity.io/legal/privacy" },
    { heading: "9. Cookies und lokale Speicherungen", text: "Das technisch notwendige Cookie „anna_cookie_consent“ speichert deine Datenschutz-Auswahl, die Version der Auswahlmöglichkeiten und deren Ablaufzeit für 180 Tage. Rechtsgrundlagen sind § 25 Abs. 2 Nr. 2 TDDDG und Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse ist die Beachtung und Verwaltung deiner Datenschutz-Auswahl.\n\nNur wenn du „Alle akzeptieren“ wählst, verwenden wir zusätzlich folgende Komfortspeicherungen: Das Cookie „anna-theme“ merkt sich dein helles oder dunkles Farbschema bis zum Ablauf deiner Einwilligung, höchstens 180 Tage. Ein Wechsel des Farbschemas verlängert diese Frist nicht. Der Eintrag „anna-site-intro-seen“ im Session Storage merkt sich bis zum Ende der Sitzung, dass die Startanimation bereits angezeigt wurde. Ohne diese Einwilligung wird das Farbschema nicht dauerhaft gespeichert; die Website bleibt nutzbar.\n\nDie Komfortspeicherungen erfolgen auf Grundlage deiner Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Über „Cookie-Einstellungen“ im Footer kannst du deine Auswahl jederzeit ändern. Mit „Nur notwendige“ widerrufst du die optionale Einwilligung; die Komfortspeicherungen werden dabei gelöscht. Der Widerruf berührt nicht die Rechtmäßigkeit der bisherigen Verarbeitung. Bei einer Änderung der optionalen Zwecke fragen wir erneut nach deiner Einwilligung. Analyse-, Profiling- oder Marketing-Cookies werden nicht eingesetzt." },
    { heading: "10. Externe Links und soziale Netzwerke", text: "Unsere Website enthält ausschließlich einfache Links zu Instagram und Pinterest. Beim bloßen Besuch unserer Website werden dadurch keine Inhalte dieser Plattformen geladen. Erst wenn du einen solchen Link aufrufst, verlässt du unsere Website; ab diesem Zeitpunkt gelten die Datenschutzbestimmungen des jeweiligen Anbieters." },
    { heading: "11. Empfänger und Drittlandübermittlungen", text: "Im Rahmen der beschriebenen Zwecke können Vercel, Resend, Cloudflare und Sanity als technische Dienstleister personenbezogene Daten erhalten. Soweit Daten außerhalb der Europäischen Union oder des Europäischen Wirtschaftsraums verarbeitet werden, erfolgt dies nur unter Beachtung der Voraussetzungen der Art. 44 ff. DSGVO, etwa auf Grundlage eines Angemessenheitsbeschlusses oder geeigneter Garantien wie EU-Standardvertragsklauseln." },
    { heading: "12. Speicherdauer", text: "Wir speichern personenbezogene Daten nur so lange, wie dies für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen. Erfolglose Projektanfragen werden sechs Monate nach dem letzten Kontakt vollständig gelöscht, sofern keine gesetzlichen Gründe für eine längere Speicherung vorliegen. Vertrags- und abrechnungsrelevante Daten werden entsprechend den gesetzlichen Aufbewahrungsfristen gespeichert." },
    { heading: "13. Deine Rechte", text: "Du hast im Rahmen der gesetzlichen Voraussetzungen das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Wenn eine Verarbeitung auf Art. 6 Abs. 1 lit. f DSGVO beruht, kannst du ihr aus Gründen widersprechen, die sich aus deiner besonderen Situation ergeben. Eine erteilte Einwilligung kannst du jederzeit mit Wirkung für die Zukunft widerrufen, ohne dass die Rechtmäßigkeit der Verarbeitung bis zum Widerruf berührt wird. Zur Ausübung deiner Rechte genügt eine Nachricht an studio@annaedition.de." },
    { heading: "14. Beschwerderecht", text: "Du hast das Recht, dich bei einer Datenschutzaufsichtsbehörde zu beschweren. Zuständig für Nordrhein-Westfalen ist insbesondere die Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW), Kavalleriestraße 2–4, 40213 Düsseldorf, https://www.ldi.nrw.de/." },
    { heading: "15. Verschlüsselte Übertragung", text: "Diese Website nutzt eine verschlüsselte HTTPS-Verbindung. Dadurch werden Daten, die du an uns übermittelst, während der Übertragung vor dem Zugriff Dritter geschützt." },
  ];
  return (
    <section className="section container legal">
      <p className="eyebrow" data-motion="load">{page?.eyebrow || "Rechtliches"}</p>
      <h1 className="display" data-motion="load" data-motion-order="1">{page?.title || "Datenschutz"}</h1>
      <p className="lede" data-motion="load" data-motion-order="2">{page?.intro || "Hier erfährst du transparent, welche Daten bei der Nutzung unserer Website verarbeitet werden und welche Rechte du hast."}</p>
      {sections.map((section) => <div data-motion="reveal" key={section.heading}><h2>{section.heading}</h2><p className="legal-text">{section.text}</p></div>)}
      <p className="legal-updated">Stand: 25. September 2026</p>
    </section>
  );
}
